version: '3.3'
services:
  app:
    env_file: .env
    build:
      context: app
    volumes:
      - files:$GLPI_VAR_DIR
      - log_glpi:$GLPI_LOG_DIR
      - conf_glpi:$GLPI_CONFIG_DIR
      - ./app/downstream.php:/var/www/glpi/inc/downstream.php
    entrypoint:
      - /root/entrypoint.sh
    depends_on:
      - db
    expose:
      - 9000
  web:
    build:
      context: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "0.0.0.0:6543:80"
  db:
    image: "mariadb:10.5"
    env_file: .env
    volumes:
      - db_glpi:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
volumes:
  db_glpi: {}
  files: {}
  conf_glpi: {}
  log_glpi: {}
