version: '3.3'
services:
  app:
    env_file: .env
    build:
      context: app
    volumes:
      - data_glpi:$GLPI_DATA
    entrypoint:
      - /root/entrypoint.sh
    depends_on:
      - db
    expose:
      - 9000
  web:
    env_file: .env
    depends_on:
      - app
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - data_glpi:$GLPI_DATA
    ports:
      - "0.0.0.0:6543:80"
  db:
    image: "mariadb:10.6"
    env_file: .env
    volumes:
      - db_glpi:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
volumes:
  db_glpi: {}
  data_glpi: {}
