---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/affinity: cookie
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: glpi-b.k8s-tests.cobayops.xyz
      paths:
        - path: /
  tls:
    - secretName: glpi-tls
      hosts:
        - glpi-b.k8s-tests.cobayops.xyz
storage:
  size: 10Gi
  accessMode: ReadWriteMany
  storageClassName: ""
  volumeName: glpi-data-b
...
