---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/affinity: cookie
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: glpi-a.k8s-tests.cobayops.xyz
      paths:
        - path: /
  tls:
    - secretName: glpi-a-tls
      hosts:
        - glpi-a.k8s-tests.cobayops.xyz
storage:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: glpi-data-a
  resources:
    requests:
      storage: 10Gi
...
