---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-data-a
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/"
    server: nfs-server.glpi-a.svc.cluster.local
  storageClassName: ""
