---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-data-b
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/"
    server: nfs-server.glpi-b.svc.cluster.local
  storageClassName: ""
