apiVersion: v1
kind: PersistentVolume
metadata:
  name: glpi-data-b
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/data/glpi-b"
    server: nfs-server.default.svc.cluster.local